In [2]:
import numpy as np
import time

In [2]:
x1 = np.array([1,2,3])
x2 = [1,2,3]

print(np.array([1,2,3]).shape)     # (3,)
print(np.array([[1,2,3]]).shape)   # (1,3)
print(np.array([[1],[2],[3]]).shape)  # (3,1)


(3,)
(1, 3)
(3, 1)


In [3]:
# multi feature dataset:
X = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
# 3 training examples and 2 features

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [5]:
print(a)
print(b)
print(a.shape, b.shape)


[1 2 3]
[4 5 6]
(3,) (3,)


In [6]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


| Operation    | Code    | Output |
| ------------ | ------- | ------ |
| Element-wise | `a * b` | vector |
| Dot product  | `a @ b` | scalar | 

Dot product : np.dot(a,b) OR a @ b

dot product : 1* 4 + 2* 5 + 3*6 = 32

element-wise multiplication : [4,10,18]

In [ ]:
# dot product vs normal multiplacation between 2 numpy arrays.
print(np.dot(a, b)) # another way of writing : a @ b
print (a * b)

32
[ 4 10 18]


: 

In [5]:
x = np.arange(1,10)
print(x.shape)

x = np.random.permutation(9)
print(x)

(9,)
[3 0 2 1 4 6 7 8 5]
